name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate the data
        run: |
          VALIDATE_DATA_OUTPUT="$(bash scripts/validate-data.sh | tr '\0' '\n')"
          if [ -n "${VALIDATE_DATA_OUTPUT}" ]; then
              echo "${VALIDATE_DATA_OUTPUT}"
              exit 1
          fi

      - name: Download the builder
        run: bash scripts/update-builder.sh

      - name: Build the mods
        run: bash scripts/build.sh --skip-validation --skip-updates
