name: Steam Workshop

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release-ck2:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Preparing the release assets
      run: |
        for GAME_ID in "CK2" "CK2HIP" "CK3" "CK3IBL" "CK3MBP" "CK3TFE" "HOI4" "HOI4TGW" "IR" "IR_AoE"; do
          mkdir "${GAME_ID}"
          wget "https://github.com/hmlendea/more-cultural-names/releases/download/${{github.ref_name}}/mcn_${GAME_ID}_${GITHUB_REF:11}.zip" -O "${GAME_ID}.zip"
          unzip "${GAME_ID}.zip" -d "${GAME_ID}/"
        done 
#        sed -i 's/^path\s*=.*/archive=\"more-cultural-names.zip\"/g' CK2/more-cultural-names.mod
#        cp CK2/more-cultural-names.mod CK2/more-cultural-names/descriptor.mod
#        cd CK2/more-cultural-names && zip -r more-cultural-names.zip . && cd -
#        mv CK2/more-cultural-names/more-cultural-names.zip CK2/
#        rm -rf CK2/more-cultural-names/
#        sed -i 's/^path\s*=.*/archive=\"hip-more-cultural-names.zip\"/g' CK2HIP/hip-more-cultural-names.mod
#        cp CK2HIP/hip-more-cultural-names.mod CK2HIP/hip-more-cultural-names/descriptor.mod
#        cd CK2HIP/hip-more-cultural-names && zip -r hip-more-cultural-names.zip . && cd -
#        mv CK2HIP/hip-more-cultural-names/hip-more-cultural-names.zip CK2HIP/
#        rm -rf CK2HIP/hip-more-cultural-names/
#
#    - name: Crusader Kings 2
#      uses: Weilbyte/steam-workshop-upload@v1
#      with:
#        appid: 203770
#        itemid: 2243430163
#        path: "CK2/"
#        changenote: "[url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
#      env:
#        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
#        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
#        STEAM_TFASEED: ${{secrets.STEAM_2FA_SEED}}
#        
#    - name: Crusader Kings 2 (HIP)
#      uses: Weilbyte/steam-workshop-upload@v1
#      with:
#        appid: 203770
#        itemid: 1175098675
#        path: "CK2HIP/"
#        changenote: "[url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
#      env:
#        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
#        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
#        STEAM_TFASEED: ${{secrets.STEAM_2FA_SEED}}

    - name: Crusader Kings 3
      uses: Weilbyte/steam-workshop-upload@v1
      with:
        appid: 1158310
        itemid: 2217534250
        path: "CK3/more-cultural-names/"
        changenote: "[url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_TFASEED: ${{secrets.STEAM_2FA_SEED}}

    - name: Crusader Kings 3 (IBL)
      uses: Weilbyte/steam-workshop-upload@v1
      with:
        appid: 1158310
        itemid: 2490281800
        path: "CK3IBL/ibl-more-cultural-names/"
        changenote: "[url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_TFASEED: ${{secrets.STEAM_2FA_SEED}}

    - name: Crusader Kings 3 (MB+)
      uses: Weilbyte/steam-workshop-upload@v1
      with:
        appid: 1158310
        itemid: 2630872947
        path: "CK3MBP/mbp-more-cultural-names/"
        changenote: "[url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_TFASEED: ${{secrets.STEAM_2FA_SEED}}

    - name: Crusader Kings 3 (SoW)
      uses: Weilbyte/steam-workshop-upload@v1
      with:
        appid: 1158310
        itemid: 2724606810
        path: "CK3SoW/sow-more-cultural-names/"
        changenote: "[url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_TFASEED: ${{secrets.STEAM_2FA_SEED}}

    - name: Crusader Kings 3 (TFE)
      uses: Weilbyte/steam-workshop-upload@v1
      with:
        appid: 1158310
        itemid: 2690444295
        path: "CK3TFE/tfe-more-cultural-names/"
        changenote: "[url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_TFASEED: ${{secrets.STEAM_2FA_SEED}}

    - name: Hearts of Iron IV
      uses: Weilbyte/steam-workshop-upload@v1
      with:
        appid: 394360
        itemid: 2459257386
        path: "HOI4/more-cultural-names/"
        changenote: "[url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_TFASEED: ${{secrets.STEAM_2FA_SEED}}

    - name: Hearts of Iron IV (TGW)
      uses: Weilbyte/steam-workshop-upload@v1
      with:
        appid: 394360
        itemid: 2725885905
        path: "HOI4TGW/tgw-more-cultural-names/"
        changenote: "[url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_TFASEED: ${{secrets.STEAM_2FA_SEED}}

    - name: Imperator Rome
      uses: Weilbyte/steam-workshop-upload@v1
      with:
        appid: 859580
        itemid: 2219177532
        path: "IR/more-cultural-names/"
        changenote: "[url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_TFASEED: ${{secrets.STEAM_2FA_SEED}}

    - name: Imperator Rome (AoE)
      uses: Weilbyte/steam-workshop-upload@v1
      with:
        appid: 859580
        itemid: 2753371253
        path: "IR_AoE/aoe-more-cultural-names/"
        changenote: "[url=https://github.com/hmlendea/more-cultural-names/releases/tag/${{github.ref_name}}]Version ${{github.ref_name}}[/url]"
      env:
        STEAM_USERNAME: ${{secrets.STEAM_USERNAME}}
        STEAM_PASSWORD: ${{secrets.STEAM_PASSWORD}}
        STEAM_TFASEED: ${{secrets.STEAM_2FA_SEED}}
