name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate the data
        run: |
          VALIDATE_DATA_OUTPUT="$(bash scripts/validate-data.sh | tr '\0' '\n')"
          if [ -n "${VALIDATE_DATA_OUTPUT}" ]; then
              echo "${VALIDATE_DATA_OUTPUT}"
              exit 1
          fi
