name: Validation

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the mods
        run: |
          VALIDATE_DATA="$(bash scripts/validate-data.sh | tr '\0' '\n')"
          if [ -n "${VALIDATE_DATA}" ]; then
              echo "Input files validation failed!"
              echo "${VALIDATE_DATA}"
              exit 1
          fi
